// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	domain "app/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CarbonClient is an autogenerated mock type for the CarbonClient type
type CarbonClient struct {
	mock.Mock
}

type CarbonClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CarbonClient) EXPECT() *CarbonClient_Expecter {
	return &CarbonClient_Expecter{mock: &_m.Mock}
}

// FetchCarbonForecast provides a mock function with given fields: ctx
func (_m *CarbonClient) FetchCarbonForecast(ctx context.Context) ([]domain.Carbon, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchCarbonForecast")
	}

	var r0 []domain.Carbon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Carbon, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Carbon); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Carbon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CarbonClient_FetchCarbonForecast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCarbonForecast'
type CarbonClient_FetchCarbonForecast_Call struct {
	*mock.Call
}

// FetchCarbonForecast is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CarbonClient_Expecter) FetchCarbonForecast(ctx interface{}) *CarbonClient_FetchCarbonForecast_Call {
	return &CarbonClient_FetchCarbonForecast_Call{Call: _e.mock.On("FetchCarbonForecast", ctx)}
}

func (_c *CarbonClient_FetchCarbonForecast_Call) Run(run func(ctx context.Context)) *CarbonClient_FetchCarbonForecast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CarbonClient_FetchCarbonForecast_Call) Return(_a0 []domain.Carbon, _a1 error) *CarbonClient_FetchCarbonForecast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CarbonClient_FetchCarbonForecast_Call) RunAndReturn(run func(context.Context) ([]domain.Carbon, error)) *CarbonClient_FetchCarbonForecast_Call {
	_c.Call.Return(run)
	return _c
}

// NewCarbonClient creates a new instance of CarbonClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCarbonClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CarbonClient {
	mock := &CarbonClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
