services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app
        restart: on-failure
        env_file:
            - .env
        environment:
            APPLICATION_PORT: 8080
        ports:
            - "8080:8080"